#################################################
# INFRASTRUCTURE YML CONFIGURATION VERSION 3.9  #
#################################################  
version: '3.9'

services:

  #################################################
  # MongoDB                                       #
  #################################################
  mongodb:
    image: mongo:${MONGO_DB_VERSION}
    container_name: ${MONGO_DB_CONTAINER_NAME}
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"
    networks:
      - mongodb_network
    volumes:
      - mongodb:/data/db

  #################################################
  # MongoDB Express                               #
  #################################################
  mongo-express:
    image: mongo-express:${MONGO_DB_EXPRESS_VERSION}
    container_name: ${MONGO_DB_EXPRESS_CONTAINER_NAME}
    restart: on-failure
    networks:
      - mongodb_network
    ports:
      - "${MONGO_DB_EXPRESS_EXPORT_PORT}:${MONGO_DB_EXPRESS_PORT}"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_DB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@${MONGO_DB_CONTAINER_NAME}:${MONGO_DB_PORT}
          
networks:
  mongodb_network:
    name: ${NETWORK_NAME}
    driver: bridge

volumes:
  mongodb:
    external: false